#!/usr/bin/env sh
# depends: buku

edit=" Edit..."
sync=" Sync..."

entries="$(buku -p --format 3 | sed 's/^\S*\s//' | sed '/^$/d')"
entries="$edit\n$sync\n$entries"

choice="$(echo "$entries" | dmenu -p 'Bookmark:')"

[ -z "$choice" ] && exit

if [ "$choice" = "$edit" ]; then
    # Open this file for editing
    alacritty --class Float,Alacritty -e fish -C "cd $PWD; vim $0"
elif [ "$choice" = "$sync" ]; then
    alacritty --class Float,Alacritty -e fish -C "
        echo -e \"--- Importing bookmarks from Firefox ---\nDefault is: n y y \";
        buku --import ~/.mozilla/firefox/haris/bookmarks.html"
else
    # Open the bookmark in firefox
    url="$(buku --sreg "^$choice\$" -n 1 --format 1 | awk '{print $2}')"
    firefox -P haris "$url"
fi
