#!/usr/bin/env sh

get_entries() {
    echo 'Hello there'
    echo 'New entry'
    # (-<>-) DON'T TOUCH THIS (new content will be added automatically here)
}

get_entries1() {

}

choice="$(get_entries | dmenu)"
