#+TITLE: Background processes
#+SETUPFILE: .setup.org
#+TAGS: service(S)

* Setup
** Desktop Environments
One of these targets is started by startx, depending on which xinitrc preset is active.
#+begin_src systemd :tangle ~/.config/systemd/user/haris-gui-i3.target
  [Unit]
  Description=Haris' i3 graphical session target
  Requires=default.target
  Requires=haris-gui-x11.target
  Requires=i3.service
  PartOf=graphical-session.target
  AllowIsolate=yes
  StopWhenUnneeded=yes
#+end_src
** Common graphical targets
#+begin_src systemd :tangle ~/.config/systemd/user/haris-gui-x11.target
  [Unit]
  Description=Haris' X11 graphical session target
  PartOf=graphical-session.target
  Requires=default.target
  Requires=graphical-session.target
  Wants=clipmenud.service
  Wants=dunst.service
  Wants=sxhkd.service
  Wants=sxhkd-private.service
  Wants=picom.service
  Wants=redshift.service
  AllowIsolate=yes
  StopWhenUnneeded=yes
#+end_src
#+begin_src systemd :tangle ~/.config/systemd/user/graphical-session.target
  [Unit]
  Description=Haris' graphical session target
  Requires=default.target
  Wants=jira-branch-transformer.service
  StopWhenUnneeded=yes
#+end_src
** WM
This target is always reached when a WM is started, regardless of which one.
#+begin_src systemd :tangle ~/.config/systemd/user/wm.target
  [Unit]
  Description=Window manager target
  Requires=default.target
  StopWhenUnneeded=yes
#+end_src
* Default
Services that run automatically upon login (TTY or graphical).
** Emacs Daemon
#+begin_src systemd :tangle ~/.config/systemd/user/emacs.service
  [Unit]
  Description=Emacs text editor
  Documentation=info:emacs man:emacs(1) https://gnu.org/software/emacs/

  [Service]
  SyslogIdentifier=emacs
  Type=forking
  Environment=COLORTERM=truecolor
  Environment=LSP_USE_PLISTS=true
  ExecStart=/usr/bin/env emacs --daemon="emacs" --no-window-system
  Restart=always
  TimeoutStartSec=1200
  TimeoutStopSec=30
  StartLimitBurst=0

  [Install]
  WantedBy=default.target
#+end_src
** VPN Notifier
#+begin_src systemd :tangle ~/.config/systemd/user/vpn-notifier.service
  [Unit]
  Description=VPN notifier

  [Service]
  SyslogIdentifier=vpn-notifier
  Environment=XDG_RUNTIME_DIR=/run/user/%U
  ExecStart=/usr/bin/env vpn-notifier

  [Install]
  WantedBy=default.target
#+end_src
** Cron
I define my main users cron jobs in files matching the glob =~/.cron.d/crontab.*=.
*** Default cron jobs
:PROPERTIES:
:header-args+: :tangle ~/.cron.d/crontab.50
:END:
Modify PATH variable to match the normal environment's value:
#+begin_src crontab
  PATH=<<eval-path-env()>>
#+end_src
**** Low battery suspend
#+begin_src crontab
  * * * * * handle-low-bat
#+end_src
**** Check website online
#+begin_src crontab
  0 */2 *   * 1-6 website-healthcheck
  0 20  */4 * 1-6 website-healthcheck --notify-success
#+end_src
**** Remind me to reissue SSL certificate
#+begin_src crontab
  0 18-23 10 */2 * notify-send 'REMINDER' 'Reissue SSL certificate for veracioux.me'
#+end_src
**** Update fish completions
#+begin_src crontab
  0 20 * * * fish -c 'fish_update_completions'
#+end_src
*** Listen/update service                                          :service:
This service updates the user's crontab when any of the custom crontab files change.
#+begin_src systemd :tangle ~/.config/systemd/user/crontab-listen-update.service
  [Unit]
  Description=Crontab change listener and updater

  [Service]
  SyslogIdentifier=crontab-listen-update
  ExecStart=/usr/bin/env crontab-listen-update
  Restart=on-failure

  [Install]
  WantedBy=default.target
#+end_src
**** Executable
#+begin_src shell :tangle ~/.local/bin/crontab-listen-update
  if ! which inotifywait 2>/dev/null; then
      echo "ERROR: inotifywait is not installed. Aborting."
      exit 1
  fi

  mkdir -p ~/.cron.d/
  while :; do
      content=''
      for file in ~/.cron.d/*; do
          echo "Read crontab file: $file"
          content="$(
              echo "$content"
              echo
              echo "############## START $file"
              echo
              cat "$file"
              echo
              echo "############## END  $file"
          )"
      done
      echo "$content" | crontab -
      echo "Resulting content of crontab:"
      crontab -l
      echo
      inotifywait -e modify -e attrib -e create -e delete ~/.cron.d/
  done
#+end_src
* Graphical session
** i3
#+begin_src systemd :tangle ~/.config/systemd/user/i3.service
  [Unit]
  Description=i3 window manager
  PartOf=haris-gui-i3.target
  After=haris-gui-i3.target
  Wants=wm.target

  [Service]
  SyslogIdentifier=i3
  Type=oneshot
  Environment=XDG_RUNTIME_DIR=/run/user/%U
  Environment=DESKTOP_SESSION=i3
  # Used by i3-sensible-terminal
  Environment=TERMINAL=alacritty
  ExecStart=/usr/bin/env i3
#+end_src
** Sxhkd
#+begin_src systemd :tangle ~/.config/systemd/user/sxhkd.service
  [Unit]
  Description=Simple X hotkey daemon
  PartOf=haris-gui-x11.target
  After=haris-gui-x11.target
  After=wm.target

  [Install]
  WantedBy=haris-gui-x11.target

  [Service]
  SyslogIdentifier=sxhkd
  Environment=XDG_RUNTIME_DIR=/run/user/%U
  ExecStart=/usr/bin/env sxhkd
  Restart=on-failure
#+end_src
*** Sxhkd Private
#+begin_src systemd :tangle ~/.config/systemd/user/sxhkd-private.service
  [Unit]
  Description=Simple X hotkey daemon (private config)
  PartOf=haris-gui-x11.target
  After=haris-gui-x11.target
  After=wm.target

  [Install]
  WantedBy=haris-gui-x11.target

  [Service]
  SyslogIdentifier=sxhkd(private)
  Environment=XDG_RUNTIME_DIR=/run/user/%U
  ExecStart=/usr/bin/env sxhkd -c %h/.private.sxhkdrc
  Restart=on-failure
#+end_src
** Picom
#+begin_src systemd :tangle ~/.config/systemd/user/picom.service
  [Unit]
  Description=Picom compositor
  PartOf=haris-gui-x11.target
  After=haris-gui-x11.target
  After=wm.target

  [Service]
  SyslogIdentifier=picom
  ExecStart=/usr/bin/env picom
  Restart=on-failure
#+end_src
** Redshift
#+begin_src systemd :tangle ~/.config/systemd/user/redshift.service
  [Unit]
  Description=Redshift blue light filter
  PartOf=haris-gui-x11.target
  After=haris-gui-x11.target
  After=wm.target

  [Service]
  SyslogIdentifier=redshift
  ExecStart=/usr/bin/env redshift
  Restart=on-failure
#+end_src
** Clipmenud
NOTE: The =CM_DIR= environment variable was overridden [[file:shells.org::(CM_DIR)][here]].
#+begin_src systemd :tangle ~/.config/systemd/user/clipmenud.service
  [Unit]
  Description=Clipboard daemon
  PartOf=haris-gui-x11.target
  After=haris-gui-x11.target

  [Service]
  SyslogIdentifier=clipmenud
  Environment=CM_DEBUG=1
  Environment=CM_MAX_CLIPS=99999
  Environment=XDG_RUNTIME_DIR=/run/user/%U
  ExecStart=/usr/bin/env clipmenud
#+end_src
** Dunst
#+begin_src systemd :tangle ~/.config/systemd/user/dunst.service
  [Unit]
  Description=Dunst notification daemon
  PartOf=haris-gui-x11.target
  After=haris-gui-x11.target

  [Service]
  SyslogIdentifier=dunst
  Environment=XDG_RUNTIME_DIR=/run/user/%U
  ExecStart=/usr/bin/env dunst
#+end_src
** Jira Branch Transformer
#+begin_src systemd :tangle ~/.config/systemd/user/jira-branch-transformer.service
  [Unit]
  Description=Jira Branch Transformer
  PartOf=graphical-session.target
  After=graphical-session.target

  [Service]
  SyslogIdentifier=jira-branch-transformer
  ExecStart=/usr/bin/env jira-branch-transformer
#+end_src
*** Executable
#+begin_src bash :tangle ~/.local/bin/jira-branch-transformer
  while :; do
      echo "Scanning clipboard..."
      cb="$(timeout 1s xsel -bo)"
      if grep -qE <<<"$cb" "^git checkout -b [A-Z]+-[0-9]+"; then
          echo "Clipboard matched. Transforming to branch name..."
          branch="$(rev <<<"$cb" | cut -f1 -d' ' | rev)"
          echo "Transformed content: $branch"
          echo -n "$branch" | xsel -b
      fi
      sleep 3
  done
#+end_src
* Helpers
#+NAME: eval-path-env
#+begin_src emacs-lisp
  (getenv "PATH")
#+end_src
* Local variables
# Local Variables:
# org-confirm-babel-evaluate: nil
# End:
