#+TITLE: Haris' Config

* Set up for use
  - Custom scripts are located in [[.haris-bin][~.haris-bin/~]]. In order to have them available
    in your PATH, you must run copy them over to ~.local/bin/~:
    #+begin_src shell
      cp --link --interactive ~/.haris-bin/* ~/.local/bin/
    #+end_src
* Installing all dependencies
  Each configuration file contains a list of dependencies for the program it
  configures. These dependencies are conveniently placed in a shell source block
  and can be exported using ~org-babel-tangle~. The export destination is
  ~/tmp/dependencies/PROGRAM_NAME.sh~. The dependencies are installed by sourcing
  these files in a POSIX-compliant shell, individually or in bulk.

  In order to install all the dependencies, simply run
  #+begin_src sh
    ./.mkdeps
  #+end_src
** TODO Not yet implemented
   This script will also take care of extracting the shell blocks from org files,
   so you don't have to do anything except answer the package manager's prompts.

   *NOTE:* The dependency scripts were made with *Arch Linux* in mind, so they use
   ~pacman~ as the package manager and ~paru~ as an AUR helper.
