#!/bin/bash

# Print out all 256 colors in the terminals

f=0
l=256

if [ -n "$1" ]; then
	l="$1"
fi

if [ -n "$2" ]; then
	f="$1"
	l="$2"
fi

(x=`tput op` y=`printf %76s`;for i in $(seq "$f" "$l");do o=00$i;echo -e ${o:${#o}-3:3} \
`tput setaf $i;tput setab $i`${y// /=}$x;done)
