git_protocol: ssh
prompt: enabled
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
    clone: repo clone
    web: repo view --web
    v: repo view
    ls: repo list
    rel: release create
    prc: pr create
    co: pr checkout
