abbr --add rm 'rm -i'
abbr --add mv 'mv -i'

alias src_fish 'source ~/.config/fish/config.fish'
alias sudo 'doas'
alias conf 'git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias sconf 'git --git-dir=$HOME/.cfg-secret/ --work-tree=$HOME'
alias term 'alacritty -e fish -C "cd (pwd)" & disown >/dev/null'
alias vifm '~/.config/vifm/scripts/vifmrun'
alias vim 'nvim'
alias vi 'command vim'
alias snips 'cd ~/.vim/snips'
alias vidir 'VISUAL=vim command vidir'
alias mutt 'neomutt'
alias '...' 'cd ../..'
alias wkpd 'wikicurses'
alias calc 'speedcrunch'
alias info 'info --vi-keys'
alias yay 'paru'
alias SSH 'eval (ssh-agent -c) && ssh-add'

abbr g 'git'
abbr p 'pacman'
abbr s 'sudo'
abbr p 'pacman'
abbr pss 'pacman -Ss'
abbr sp 'sudo pacman'
abbr sps 'sudo pacman -S'
abbr spr 'sudo pacman -R'
abbr py 'python'

set aur 'aur@aur.archlinux.org'
