abbr --add rm 'rm -i'
abbr --add mv 'mv -i'

alias src_fish 'source ~/.config/fish/config.fish'
alias proj 'exec proj'
alias cf 'git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias sconfig 'git --git-dir=$HOME/.cfg-secret/ --work-tree=$HOME'
alias term 'alacritty -e fish -C "cd (pwd)" & disown >/dev/null'
alias vifm '~/.config/vifm/scripts/vifmrun'
alias vim 'nvim'
alias vi 'nvim'
alias vidir 'VISUAL=vim command vidir'
alias mutt 'neomutt'
alias '...' 'cd ../..'
alias wkpd 'wikicurses'
alias calc 'speedcrunch'
alias info 'info --vi-keys'
alias py 'python'

set aur 'aur@aur.archlinux.org'
