#!/usr/bin/env sh

c=~/.config

case "$1" in
    fish)
        echo $c/fish/config.fish
        ;;
    alias)
        echo $c/fish/alias.fish
        ;;
    fish-misc)
        echo $c/fish/functions/misc.fish
        ;;
    fish-com)
        echo $c/fish/completions/misc.fish
        ;;
    vim)
        echo ~/.vimrc
        ;;
    nvim)
        echo $c/nvim/init.vim
        ;;
    vifm)
        echo $c/vifm/vifmrc
        ;;
    git)
        echo ~/.gitconfig
        ;;
    i3)
        echo $c/i3/config
        ;;
    i3status)
        echo $c/i3status/config
        ;;
    picom)
        echo $c/picom.conf
        ;;
    ff)
        echo ~/.mozilla/firefox/haris/chrome/userChrome.css
        ;;
    ff-min)
        echo ~/.mozilla/firefox/minimal/chrome/userChrome.css
        ;;
    schim)
        echo $c/schim/schim.conf
        ;;
    schim-v)
        echo $c/schim/volatile.conf
        ;;
esac
