#!/bin/bash

c=~/.config

case "$1" in
	vim)
		echo ~/.vimrc
		;;
	nvim)
		echo $c/nvim/init.vim
		;;
	qtile)
		echo $c/qtile/config.py
		;;
	fish)
		echo $c/fish/config.fish
		;;
	alias)
		echo $c/fish/alias.fish
		;;
    fish-misc)
        echo $c/fish/functions/misc.fish
		;;
	firefox)
		echo ~/.mozilla/firefox/haris/chrome/userChrome.css
		;;
	alacritty)
		echo $c/alacritty/alacritty.yml
		;;
	git)
		echo ~/.gitconfig
		;;
	vifm)
		echo $c/vifm/vifmrc
		;;
	mime)
		echo $c/mimeapps.list
		;;
	mutt)
		echo $c/mutt/muttrc
		;;
	emacs)
		echo ~/.emacs.d/haris-config.el
		;;
	spacemacs)
		echo ~/.spacemacs
		;;
esac
