#!/bin/bash

# Find the html documentation of the current project and open it in firefox

function open() {

	shopt -s globstar

    # Doesn't work if the path contains spaces, but who cares
    if  cd $(echo docs/_build/html | tr ' ' '\n' | head -1) ||
        cd $(echo **/docs/_build/html | tr ' ' '\n' | head -1) ||
        cd $(echo **/_build/html | tr ' ' '\n' | head -1) ||
        cd $(echo **/html | tr ' ' '\n' | head -1)
    then
		firefox -P minimal ./index.html & disown
	fi 2>/dev/null

}

export -f open
timeout 2s bash -c open
