#!/usr/bin/env bash

# Get list of all public keys
keylist=($(gpg --list-public-keys Haris | grep '^\s' | sed 's/^\s*//g'))

entries="$(
    for key in "${keylist[@]}"; do
        # Get info for key
        keyinfo="$(gpg --list-public-keys | grep "$key" -A1)"
        # Get email of key owner
        email="$(echo "$keyinfo" | grep '<.*>' | sed 's/^.*\]//')"
        echo "$key" "$email"
    done
)"
let n=$(echo "$entries" | wc -l)

choice="$(echo "$entries" | dmenu -l $n -p 'GPG:')"

echo "$choice" | awk '{print $1}' | xsel -b
