#!/usr/bin/env bash

edit=" Edit..."

entries="$(echo "$edit"; cd ~/mail && command ls)"

choice="$(echo "$entries" | dmenu -p mail -l $(echo "$entries" | wc -l))"

[ -z "$choice" ] && exit

if [ "$choice" = "$edit" ]; then
    gvim "$0"
elif [ "${choice//*@/}" = 'gmail.com' ] || [ "${choice//*@/}" = 'etf.unsa.ba' ]; then
    auto-browser -P haris "mail.google.com/mail/?authuser=$choice"
fi
