#!/usr/bin/env sh

# Open a website in Firefox
# Suggests bookmarks managed by buku, but you can input any URL

# If a librewolf window is currently active, open the link in the active window
if xprop -id "$(xdotool getactivewindow)" | grep -qi 'librewolf'; then
    new_window=''
else
    new_window=--new-window
fi

edit=" Edit..."
sync=" Sync..."

entries="$(buku -p --format 30 | grep -v '^$')"
entries="$edit\n$sync\n$entries"

choice="$(echo "$entries" | dmenu -p 'Open:')"

[ -z "$choice" ] && exit

if [ "$choice" = "$edit" ]; then
    # Open this file for editing
    gvim "$0"
elif [ "$choice" = "$sync" ]; then
    alacritty --class Float,Alacritty -e fish -C "
        echo -e \"--- Importing bookmarks from Firefox ---\nDefault is: n y y \";
        buku --import ~/.mozilla/firefox/haris/bookmarks.html"
else
    # Try to open it as a bookmark in firefox
    url="$(buku --sreg "^$choice\$" -n 1 --format 10 | grep -v 'waiting for input')"
    [ -z "$url" ] && url="$choice"
    echo "$url" | grep -q 'meet\.google' && /bin/firefox $new_window -P haris "$url" || firefox $new_window -P haris "$url"
fi
