#!/usr/bin/env sh

# Open a website in Firefox
# Suggests bookmarks managed by buku, but you can input any URL

edit=" Edit..."
sync=" Sync..."

entries="$(buku -p --format 3 | sed 's/^\S*\s//' | sed '/^$/d')"
entries="$edit\n$sync\n$entries"

choice="$(echo "$entries" | dmenu -p 'Open:')"

[ -z "$choice" ] && exit

if [ "$choice" = "$edit" ]; then
    # Open this file for editing
    gvim "$0"
elif [ "$choice" = "$sync" ]; then
    alacritty --class Float,Alacritty -e fish -C "
        echo -e \"--- Importing bookmarks from Firefox ---\nDefault is: n y y \";
        buku --import ~/.mozilla/firefox/haris/bookmarks.html"
else
    # Try to open it as a bookmark in firefox
    url="$(buku --sreg "^$choice\$" -n 1 --format 1 | awk '{print $2}')"
    [ -z "$url" ] && url="$choice"
    firefox -P haris "$url"
fi
