#!/usr/bin/env sh

# Open a website in Firefox
# Suggests bookmarks managed by buku, but you can input any URL

edit=" Edit..."
sync=" Sync..."

entries="$(buku -p --format 30 | grep -v '^$')"
entries="$edit\n$sync\n$entries"

choice="$(echo "$entries" | dmenu -p 'Open:')"

[ -z "$choice" ] && exit

if [ "$choice" = "$edit" ]; then
    # Open this file for editing
    gvim "$0"
elif [ "$choice" = "$sync" ]; then
    alacritty --class Float,Alacritty -e fish -C "
        echo -e \"--- Importing bookmarks from Firefox ---\nDefault is: n y y \";
        buku --import ~/.mozilla/firefox/haris/bookmarks.html"
else
    # Try to open it as a bookmark in firefox
    url="$(buku --sreg "^$choice\$" -n 1 --format 10 | grep -v 'waiting for input')"
    [ -z "$url" ] && url="$choice"
    # All google links shall be opened in firefox
    echo "$url" | grep -q 'google' && browser="$(echo "$browser" | sed 's_librewolf_/bin/firefox/')"
    auto-browser -P haris "$url"
fi
