#!/usr/bin/env bash

# Select an app and copy its OTP to clipboard

cd ~

entries="$(
    fd 'otp-secret.gpg' .password-store -x echo {//} \
        | sed 's:^\.password-store/\?::'
)"

choice="$(echo "$entries" | dmenu -l 10 -p 'OTP:')"

[ -z "$choice" ] && exit 1

otp "$choice" | xsel -b
notify-send "OTP" "Saved to clipboard"
