#!/usr/bin/env sh

install=" Install..."
about=" About..."
remove=" Remove..."
manage=" Manage..."
update=" Update..."
keyring=" Keyring..."
edit=" Edit..."

print_options() {
    echo "$install"
    echo "$about"
    echo "$update"
    echo "$remove"
    echo "$manage"
    echo "$keyring"
    echo "$edit"
}

choice="$(print_options | dmenu -l $(print_options | wc -l))"

case "$choice" in
    "$install")
        choice="$(pacman -Ssq | dmenu -l 20)"
        [ -z "$choice" ] && exit
        alacritty --class Float,Alacritty -e fish -C "paru $choice" && exit
        ;;
    "$about")
        choice="$(echo "$(pacman -Qq)" | dmenu -p 'About:' -l 20)"
        [ -z "$choice" ] && exit
        alacritty --class Float,Alacritty -e fish -C "pacman -Qi $choice" && exit
        ;;
    "$update")
        alacritty --class Float,Alacritty -e fish -C "paru -Syu"
        ;;
    "$remove")
        choice="$(pacman -Qq | dmenu -l 20)"
        [ -z "$choice" ] && exit
        alacritty --class Float,Alacritty -e fish -C "sudo pacman -R $choice" && exit
        ;;
    "$manage")
        gvim "$(fcmd system-install)"
        ;;
    "$keyring")
        alacritty --class Float,Alacritty -e fish -C "sudo pacman -Sy archlinux-keyring && exit"
        ;;
    "$edit")
        gvim "$0"
        ;;
esac
