#!/usr/bin/env sh

# If a librewolf window is currently active, open the link in the active window
if xprop -id "$(xdotool getactivewindow)" | grep -qi 'librewolf'; then
    new_window=''
else
    new_window=--new-window
fi
choice="$(echo -n '' | dmenu -p 'Search:')" && firefox -P haris $new_window \
    "$(printf "$(links | grep duckduckgo)" "$choice")"
