#!/usr/bin/env sh

choice="$(echo "Shutdown\nSuspend\nReboot..." | dmenu)"

# No choice, bye-bye
[ -z "$choice" ] && exit

if [ "$choice" = "Shutdown" ]; then

    choice="$(echo " No\n Yes, shutdown" | dmenu -p 'Sure?')"
    [ "$choice" = " Yes, shutdown" ] && shutdown now

elif [ "$choice" = "Suspend" ]; then

    systemctl suspend -i

elif [ "$choice" = "Reboot..." ]; then

    print_entries() {
        # Extract only lines with menu entries from grub
        grep "menuentry '\|submenu '" /boot/grub/grub.cfg   |\
        # Only top-level menus are considered
        grep -v -P '\t'                                     |\
        # Take only the entry name
        sed "s_\S* '\([^']*\)'.*_\1_"                       |\
        # Add numbers
        nl -w 1 -v 0 -n rn | sed -E 's/\s+/ /g'
    }

    entries="$(print_entries)"
    choice="$(echo "$entries" | dmenu -l $(echo "$entries" | wc -l))"
    [ -z "$choice" ] && exit
    # grub-reboot should be allowed passwordless in sudo (or doas)
    sudo grub-reboot "$(echo "$choice" | cut -c 1)"
    sudo reboot
fi
