#!/usr/bin/env sh

edit=" Edit..."

entries="$(echo "$edit"
            ls ~/projects/*/TODO.org |
                while read p; do
                    basename "$(dirname "$p")"
                done)"

choice="$(
    echo "$entries" | dmenu -p TODO:
)"

if [ "$choice" = " Edit..." ]; then
    cd "$(dirname "$0")"; gvim "$0"
else
    emacsclient --create-frame "$HOME/projects/$choice/TODO.org"
fi
