#!/usr/bin/env bash

edit=" Edit..."
lookup="$(ls ~/proj/*/TODO.org ~/proj/drytoe/*/TODO.org \
    ~/data/personal/todos/*/TODO.org)"
echo "$lookup"

entries="$(echo "$edit"
           echo "$lookup" |
           while read p; do
               basename "$(dirname "$p")"
           done)"

choice="$(
    echo "$entries" | dmenu -p TODO:
)"

[ "$?" != 0 ] && exit 1

if [ "$choice" = " Edit..." ]; then
    cd "$(dirname "$0")"; gvim "$0"
else
    myemacs -c $(echo "$lookup" | grep "$choice/TODO.org")
fi
