#!/usr/bin/env python3

# Choose a font-awesome icon from dmenu and copy it

from urllib.request import urlopen
from subprocess import run, PIPE
import os.path
import yaml

# ┏━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ Prepare the icon list ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━┛

cache_file = os.path.expanduser('~/.cache/font-awesome-icon-list.yml')

# Read the yml file from cache, or download it from GitHub
if os.path.exists(cache_file):
    text = open(cache_file).read()
else:
    url = 'https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/metadata/icons.yml'
    data = urlopen(url).read()
    text = data.decode('utf-8')
    open(cache_file, 'w').write(text)

# Read the YAML file
data = yaml.load(text, yaml.Loader)

# ┏━━━━━━━━━━━━━━━━━━━━┓
# ┃ Add custom options ┃
# ┗━━━━━━━━━━━━━━━━━━━━┛
top_entries =   [
    ' Edit...',
    ' FontAwesome...',
    ' From code...',
    ' Get code...',
]

char_entries = []
# Create a (decorated) list of entries
for key in data.keys():
    unicode = int(data[key]['unicode'], base=16)
    char_entries.append(chr(unicode) + ' ' + key)

def add_custom(char):
    global char_entries
    char_entries.append(char + ' [custom]')

# ┏━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ Add custom characters ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━┛
add_custom('├ |-')
add_custom('└ |_')
add_custom('─ --')
add_custom('┃┗━┛┏━┓ ||')
add_custom('š .sh')
add_custom('ć .ch meko')
add_custom('č .ch tvrdo')
add_custom('đ .dj')
add_custom('ž .zj')

# Form entry lists as multi-line strings
char_entries = '\n'.join(char_entries)
# Add options and character entries together
top_entries  = '\n'.join(top_entries) + '\n' + char_entries

# Run dmenu and get user choice
p = run(['dmenu'], stdout=PIPE, input=top_entries, encoding='utf-8')
choice = p.stdout[:-1]

def copy_to_clipboard(text):
    run(['xsel', '-b'], input=text, encoding='utf-8')

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃ Actions based on user's choice ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
if choice[2:] == 'Edit...': # Open this file for editing
    run(['alacritty', '--class', 'Float,Alacritty', '-e', 'fish', '-C',
         'cd (dirname ' + __file__ + '); vim -c "norm 45z." ' + __file__])
elif choice[2:] == 'FontAwesome...':
    run(['firefox', 'https://fontawesome.com/cheatsheet'])
elif choice[2:] == 'From code...':
    p = run(['dmenu', '-p', 'Code:'], stdout=PIPE, input=char_entries, encoding='utf-8')
    open('/home/haris/src/testlog', 'w').write(choice)
    code = p.stdout[:-1]
    if choice:
        copy_to_clipboard(chr(int(code, base=16)))
elif choice[2:] == 'Get code...':
    p = run(['dmenu', '-p', 'Character:'], stdout=PIPE, input=char_entries, encoding='utf-8')
    choice = p.stdout[:-1]
    if choice:
        copy_to_clipboard(str(ord(choice[0])))
elif choice:
    copy_to_clipboard(choice.split(' ')[0])
