#!/bin/bash

# Distribution-specific location of media directory
# Arch Linux
	media=/run/media
# Other
#	media=/media

USER=/home/haris

mkdir -p $media/haris/ssd
mount /dev/sdc1 /run/media/haris/ssd

mkdir -p "$USER"/mnt/ssd
mount --bind $media/haris/ssd "$USER"/mnt/ssd
