#!/bin/bash
# Mount the remaining partitions

mkdir -p /run/media/haris/D
mkdir -p /run/media/haris/E
mkdir -p /run/media/haris/F

mount /dev/sda4 /run/media/haris/D
mount /dev/sdb5 /run/media/haris/E
mount /dev/sdb7 /run/media/haris/F

################################################################

# Mount all my data that is stored on external drives, to ~/

# Distribution-specific location of media directory
# Arch Linux
	media=/run/media
# Other
#	media=/media

function automount {
	mkdir -p "$2"
	mount --bind "$1" "$2"
}

USER=/home/haris

automount $media/haris/D/my-data "$USER"/data
automount $media/haris/D/my-data/projects "$USER"/projects
automount $media/haris/D/my-data/personal/wiki "$USER"/wiki
automount $media/haris/D/my-data/templates "$USER"/templates

automount $media/haris/F/src "$USER"/src
automount $media/haris/F "$USER"/mnt/f
