#!/bin/bash

##################################
# My rsync synchronization rules #
##################################

# Change this accordingly
machine_name='acer-root'

review_file='/tmp/synchro-review.txt'
redirect=''
dry_run=''

# Was the dry-run argument specified?
if [ "$1" == '--dry-run' ] || [ "$1" == '-n' ]
then
	dry_run='--dry-run'
	redirect="| tee -a $review_file"
	echo > "$review_file" # Clear the file
	dest="$2"
else
	dest="$1"
fi

# If no destination was specified, use the default one
if [ -n "$dest" ]; then
	dest="$dest"
else
	dest=~/mnt/ssd
fi

# Perform rsync but mkdir if necessary
function rsync_call() {
	mkdir -p "$dest/$2/"

	eval rsync -rvu $dry_run --exclude-from="$HOME"/.rsync-exclude \
		"$1" "$dest/$2/" \
		$redirect
}

rsync_call ~/data/ my-data
rsync_call ~/.cfg/ haris/cfg
rsync_call ~/.cfg-secret/ haris/scfg
rsync_call /etc/ "$machine_name/etc"
rsync_call /usr/share/backgrounds/ "$machine_name/usr/share/backgrounds"

[ -n "$redirect" ] && vim "$review_file"
