#!/bin/bash

umount /dev/sda4
umount /dev/sdb5
umount /dev/sdb7

USER=/home/haris

umount "$USER"/data
umount "$USER"/projects
umount "$USER"/wiki
umount "$USER"/templates
umount "$USER"/src

umount "$USER"/mnt/f
