#!/usr/bin/env bash

# Create an ad-hoc file, edit it in $EDITOR and then print its path. If a '-'
# argument is given, the file contents are printed instead of its path.

destdir="/tmp/adhoc-files"
mkdir -p "$destdir"
cd "$destdir"

if [ "$#" != 0 ] && [ "$1" = "-" ]; then
    print_content=true
    files=("${@:2}")
else
    files=("$@")
fi

# Convert files to realpaths
readarray -t files < <(realpath "${files[@]}" 2>/dev/null)

if [ -z "$files" ]; then
    files=("$(mktemp "$destdir"/XXXXXXXXXXX)")
fi

term --class Float -e fish -c "nvim ${files[*]}"

if [ -n "$print_content" ]; then
    cat "${files[@]}"
else
    realpath "${files[@]}"
fi

