#!/usr/bin/env sh

# Clone my dotfiles repo into $HOME/.cfg, as per my usual strategy

conf() {
    git --work-tree="$HOME" --git-dir="$HOME/.cfg" "$@"
}

conf clone https://github.com/veracioux/dotfiles --bare "$HOME/.cfg"

conf remote set-url origin_ro https://github.com/veracioux/dotfiles
conf remote set-url origin git@github.com:veracioux/dotfiles
conf checkout

touch ~/.alias-tmp
touch ~/.alias-gui-tmp
touch ~/.sxhkd.tmp

touch ~/.config/fish/tmp.fish
