#!/usr/bin/env sh

if [ "$TERM" = "linux" ]; then
    "$@"
    exit
fi

"$@" && notify-send "Command $(echo $@) exited successfully." || {
    err=$?
    notify-send -u critical "Command $(echo $@) exited with error $err."
}
return $err
