#!/usr/bin/env bash

# Fake gvim which will just launch a terminal with neovim in it

for arg in "$@"; do
    # Hacky solution that will open files in real gvim when opened by xdg-open
     if [ "$arg" = "-f" ]; then /usr/bin/gvim "$@"; exit; fi
done

# nvim is launched through the shell because otherwise it behaves weirdly
# All arguments are surrounded with ''
FISH_CMD="$(printf "%q " nvim "$@")"

if [ ! -t 0 ]; then
    # Input is from a PIPE
    pipe_input="$(mktemp -t XXXXXXXXXXXXXXXX)"
    cat > "$pipe_input"
    FISH_CMD="cat $pipe_input | $FISH_CMD"
fi

alacritty --class Float,Alacritty -e fish -C "$FISH_CMD"

if [ ! -t 0 ]; then
    # Input is from a PIPE
    rm -f "$pipe_input"
fi
