#!/usr/bin/env bash

# List of all blocks
listing="$(lsblk --list -o NAME,LABEL)"

# ... with header removed
items="$(echo "$listing" | tail -n +2 | sed 's/.*/"&"/' | nl --number-width=1)"
# number of lines
lineno="$(echo "$items" | wc -l)"

# Open file descriptor 3
exec 3>&1
# Show dialog and store id of selection
id=$(eval dialog --default-item $lineno --menu '"Choose a device/partition:"' 60 50 $lineno $items 2>&1 1>&3)
[ "$?" != 0 ] && exit 1     # Dialog exited with error
# Select mounting directory
mount_dir="$(dialog --fselect ~/mnt/ 60 50 2>&1 1>&3)"
[ "$?" != 0 ] && exit 1     # Dialog exited with error

# Clear but keep scrollback buffer
clear -x

if [ ! -d "$mount_dir" ]; then # Nonexisting mount directory
    read -n 1 -p\
        "The directory $mount_dir does not exist and will be created. Continue?  [y/n]: " \
        choice 1>/dev/null
    [ "$choice" != "y" ] && exit 1
    echo # newline
    mkdir "$mount_dir"
fi

# Get path to selected device
device=/dev/"$(echo "$items" | sed -n ${id}p | sed 's_.*"\(\S*\)\s.*_\1_')"

read -n 1 -p\
   "$device will be mounted at $mount_dir. Continue? (requires sudo) [y/n]: " \
    choice
echo # newline

[ "$choice" != "y" ] && exit 1

# Mount the device at last
sudo mount "$device" "$mount_dir" -o umask=002,uid=$(id -u),gid=$(id -g)

echo -e "$mount_dir" > /tmp/imount_directory
chmod a+rw /tmp/imount_directory
