#!/usr/bin/env bash

shopt -s expand_aliases

alias pass=/usr/bin/pass

# Add a password read directly from stdin (without prompting to interactively
# enter it)
if [ "$1" = "add" ]; then
    dest=~/.password-store/"$2"
    destdir="$(dirname "$dest")"
    mkdir -p "$destdir"
    cat | gpg -e -o- -r "$(cat ~/.password-store/.gpg-id)" > "$dest".gpg
else
    pass "$@"
fi
