#!/usr/bin/env sh

for arg in "$@"; do
    [ ! -e "$arg" ] && continue
    arg="$(realpath "$arg")"
    if echo "$arg" | grep -q '^/home' && echo "$arg" | grep -qv '^/home/[^/]\+/[^/]\+'; then
        echo "WTF: Trying to delete a home directory???"
        exit 1
    fi
done
/usr/bin/rm "$@"
