#!/usr/bin/env bash

official() {
	pacman -S $@
}

unofficial() {
	paru -S $@
}

npm() {
	command npm install -g "$@"
}

# Keyboard setup step, don't need it with this laptop.
ip link
echo "Setup your wifi network using iwctl."
iwctl
echo -e '[Network]\nEnableIPv6=true' >> /etc/iwd/main.conf
ping archlinux.org # verify connection
timedatectl set-ntp true
echo 'Now run cfdisk /dev/<device_id>'
# TODO
mount 'system_partition' /mnt
mount '/dev/<efi-partition>' /mnt/boot
pacstrap /mnt base linux linux-firmware vim doas iwd man mandb sudo curl

pacman -Sy

genfstab -L /mnt >> /mnt/etc/fstab

arch-chroot /mnt

# Context-specific
ln -sf /usr/share/zoneinfo/Europe/Sarajevo /etc/localtime

hwclock --systohc

echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen
locale-gen
echo 'LANG=en_US.UTF-8' >> /etc/locale.conf
# TODO set the console keyboard layout

echo 'haris-gusic' > /etc/hostname
# maybe run 'mkinitcpio -P'

pacman -Sy

official grub efibootmgr


# Swapfile

exit # TODO FIXME

# Essential
official base-devel git dash doas fish neovim

# Create user
for group in uucp video davfs2 fuse tty docker; do
	groupadd "$group"
done
useradd -m -G log,lock,wheel,tty,audio,lp,uucp,video,davfs2,fuse -s /usr/bin/dash haris

# TODO After first login
git clone 'https://github.com/Morganamilo/paru' /tmp/paru

# For dual-boot setups, configure the clock TODO

# A list of packages to install on a fresh system install

# System stuff
official pacman-contrib etckeeper
# Network
official networkmanager iw wpa_suplicant proton
official bluez bluez-libs bluez-tools bluez-utils
# Low-level
official xorg-server xorg-server-common xf86-video-vesa xorg-setxkbmap \
	xorg-xev xorg-xmodmap xorg-xprop xorg-xrandr xorg-xrdb xorg-xset \
	xorg-xsetroot xorg-xinit
official acpilight qtile i3-gaps picom xbindkeys sxhkd

# Editors and viewers
official lsd xarchiver ueberzug imagemagick python-sphinx emacs
official vifm ueberzug ffmpegthumbnailer ranger nemo gsettings
official zathura zathura-pdf-mupdf
official gimp inkscape poppler xournalpp

# Programming
official python python-pip python-sphinx

# Utilities
official xsel xclip moreutils rsync findutils dialog fzf clipmenu entr gnu-netcat cronie
official xss-lock pass
official flameshot zbar
official neomutt translate-shell transmission-cli
official speedcrunch
unofficial urlview buku-git asciinema dragon-drag-and-drop
unofficial git-extras
official ascii

# Plugins
official fisher firefox-tridactyl

# Resources
official adobe-source-code-pro-fonts ttf-lato ttf-font-awesome
unofficial dracula-gtk-theme ttf-spacemono

## Dependencies
~/.vim/.dependencies.sh
~/.mozilla/firefox/pacman.sh

git clone 'https://github.com/syl20bnr/spacemacs' ~/.emacs.d

# Fix wifi dropping issue
echo -e '[connection]\nwifi.powersave = 2' > \
/etc/NetworkManager/conf.d/default-wifi-powersave-on.conf

export me='veracioux.herokuapp.com'
