#!/usr/bin/env sh

# Wrapper script for vim which:
#   1. By default opens vim with a configuration for displaying man pages,
#       without loading unnecessary plugins
#   2. If the --floating option is provided, opens a popup window

[ "$1" = '--floating' ] && {
    shift
    cat > /dev/shm/viman
    alacritty --class Float,Alacritty -e fish \
        -C "cat /dev/shm/viman | nvim --cmd 'let g:haris_man = \"true\"' +Man! $*"
    rm -f /dev/shm/viman
} || {
    nvim --cmd 'let g:haris_man = "true"' +Man! "$@"
}

