#!/bin/bash
# Open project of given name, designed to be launched by keyboard shortcut

init_dir="$(pwd)"
trap "cd "$init_dir"; exec $SHELL" EXIT
if [ ! -d "~/projects/" ]; then
  cd ~/projects/
  ls
  read -p "Enter project folder name: " name
  cd $(find -maxdepth 1 -iname "*$name*"| grep -v ^'\.\/\.' | head -1)
  clear
  exec $SHELL
else
  echo "Project folder does not exist. Have you mounted?"
fi
