#!/bin/bash

custom_install() {
	cd ~/scripts/local/pkgbuild
	mkdir -p /tmp/"$1"/
	cp $(echo $1 | tr [:lower:] [:upper:]) /tmp/"$1"/PKGBUILD
	cd /tmp/"$1"
	makepkg --skipinteg -f --install
}

pacman -S neovim fish

useradd -m -G log,lock,wheel,tty,audio,lp,uucp,video,haris -s fish haris

# For dual-boot setups, configure the clock TODO

# A list of packages to install on a fresh system install

# System stuff
pacman -S base-devel sudo
pacman -S etckeeper
# Network
pacman -S networkmanager iw wpa_suplicant
# Low-level
pacman -S xorg acpilight qtile i3-gaps picom
yay -S tdm polybar

# Editors and viewers
pacman -S exa xarchiver ueberzug imagemagick python-sphinx emacs
pacman -S vifm ueberzug ffmpegthumbnailer ranger nemo gsettings
pacman -S zathura zathura-pdf-mupdf
pacman -S gimp inkscape poppler xournalpp

# Programming
pacman -S python python-pip

# Utilities
pacman -S git xsel moreutils rsync findutils dialog fzf
pacman -S neomutt translate-shell
pacman -S speedcrunch
yay -S urlview buku-git asciinema

# Plugins
pacman -S fisher vundle firefox-tridactyl

# Resources
pacman -S adobe-source-code-pro-fonts ttf-lato
yay -S dracula-gtk-theme

## Additional installs using various methods
	# spacemacs

## Dependencies
~/.vim/pacman.sh
~/.mozilla/firefox/pacman.sh

git clone 'https://github.com/syl20bnr/spacemacs' ~/.emacs.d

# Fix wifi dropping issue
echo -e '[connection]\nwifi.powersave = 2' > \
/etc/NetworkManager/conf.d/default-wifi-powersave-on.conf

